# Configure and deploy the load balancer(s).

- hosts: all

  tasks:

  - name: Upgrade all installed packages via yum
    yum:
      name: '*'
      state: latest

  - name: Install haproxy 
    yum:
      name: haproxy
      state: latest

  - name: Install haproxy 
    yum:
      name: keepalived
      state: latest


# Edit the rsyslog.conf file

  - lineinfile:
      dest: /etc/rsyslog.conf 
      insertafter: 'local7.*'
      line: 'local2.*        /var/log/haproxy'
      backup: yes

  - lineinfile:
      dest: /etc/rsyslog.conf 
      insertafter: 'local2.*'
      line: 'local3.*        /var/log/haproxy-access_log'
      backup: yes

# Copy over templates

  - template:
      src: /Users/rob.birdwell/Downloads/Playbooks/templates/syslog
      dest: /etc/sysconfig/syslog
      owner: root
      group: root
      mode: 0644

  - template:
      src: /Users/rob.birdwell/Downloads/Playbooks/templates/provhaproxy.cfg
      dest: /etc/haproxy/haproxy.cfg 
      owner: root
      group: root
      mode: 0644

# Server-specific template copy

- hosts: 100.106.12.52

  tasks: 

  - template:
      src: /Users/rob.birdwell/Downloads/Playbooks/templates/keepalived.conf.provision1
      dest: /etc/keepalived/keepalived.conf 
      owner: root
      group: root
      mode: 0644

  - template:
      src: /Users/rob.birdwell/Downloads/Playbooks/templates/provhaproxy1.cfg
      dest: /etc/haproxy/haproxy.cfg
      owner: root
      group: root
      mode: 0644

- hosts: 100.106.12.53

  tasks: 

  - template:
      src: /Users/rob.birdwell/Downloads/Playbooks/templates/keepalived.conf.provision2
      dest: /etc/keepalived/keepalived.conf 
      owner: root
      group: root
      mode: 0644

  - template:
      src: /Users/rob.birdwell/Downloads/Playbooks/templates/provhaproxy2.cfg
      dest: /etc/haproxy/haproxy.cfg
      owner: root
      group: root
      mode: 0644

- hosts: 100.106.12.42

  tasks: 
  
  - template:
      src: /Users/rob.birdwell/Downloads/Playbooks/templates/keepalived.conf.provision3
      dest: /etc/keepalived/keepalived.conf 
      owner: root
      group: root
      mode: 0644
              
  - template:
      src: /Users/rob.birdwell/Downloads/Playbooks/templates/provhaproxy3.cfg
      dest: /etc/haproxy/haproxy.cfg
      owner: root
      group: root
      mode: 0644

- hosts: 100.106.12.44

  tasks: 
  
  - template:
      src: /Users/rob.birdwell/Downloads/Playbooks/templates/keepalived.conf.provision4
      dest: /etc/keepalived/keepalived.conf 
      owner: root
      group: root
      mode: 0644

  - template:
      src: /Users/rob.birdwell/Downloads/Playbooks/templates/provhaproxy4.cfg
      dest: /etc/haproxy/haproxy.cfg
      owner: root
      group: root
      mode: 0644
              
# Start haproxy and keepalived

- hosts: all

  tasks:

  - service:
      name: keepalived
      state: restarted

  - service:
      name: haproxy
      state: restarted

